Scrape Party List Members
everypolitician-scrapers/mongolia-khurai-wp-multiple-terms pull request #6
Opened 2016-10-25 14:02 UTC by ondenman

The 2012 term differs from the 2008 and 2016 terms because it
contains party list members. The party list members are listed
in a table with a layout that differs from that of the constituency
list members.

Previously, the constituency name for each party list member was being set as that member's personal name.
The new class returns nil for this field as party list members do not have a constituency.

The class inherits directly from NokogiriDocument as fields created with FieldSerializer cannot be inherited currently.

2016-10-25 15:01 UTC, tmtmtmtm requested changes

2016-10-25 15:01 UTC, tmtmtmtm commented on lib/member_table.rb
> +  end
what is this method for? I can't see how it's used.

2016-10-25 15:01 UTC, tmtmtmtm commented on lib/term_page.rb
> +    MemberTable.new(table: constituency_table, member_class: constituency).members |
`|` seems a little surprising here. Should this just be `+`?

2016-10-25 15:01 UTC, tmtmtmtm commented on lib/term_page.rb
> +  end
This is quite a confusing method. What is the `constituency` of a TermPage?

2016-10-25 15:01 UTC, tmtmtmtm commented on lib/member_table.rb
> +    super(table)
It seems like quite a bad idea to have `new` in a subclass have an entirely different signature to the parent class. If you really need to switch to named parameters here (and I'm not sure that you do), then you should probably change NokogiriDocument to use the same approach everywhere.

2016-10-31 10:28 UTC, tmtmtmtm requested changes

2016-10-31 10:28 UTC, tmtmtmtm commented on lib/nokogiri_document.rb
> +  def initialize(noko, content_class = nil)
NokogiriDocument should really be treated as if it were a separate standalone gem that *all* scrapers can use, but which we just haven't extracted yet — i.e. you shouldn't be changing it unless that's going to become part of that gem. And it's definitely not clear to me from what's going on here what this extract functionality is or does or whether we'd need to include something like that there. What would the documentation for this be if it were moved up into a gem for every scraper?

2016-10-31 10:28 UTC, tmtmtmtm commented on lib/term_page.rb
> +    MemberTable.new(party_list_table, party_list_member_class).members
This seems like you should really be instantiating two different classes, e.g. ConstituencyMemberTable, and PartyListMemberTable.

2016-11-14 10:39 UTC, ondenman commented
@tmtmtmtm 👀

2017-01-04 11:14 UTC, tmtmtmtm commented
@ondenman assuming this is still required, it's going to need rejigged in line with us now using `Scraped`…

2017-01-06 10:07 UTC, ondenman commented
This PR was superseded by https://github.com/everypolitician-scrapers/mongolia-khurai-wp-multiple-terms/pull/9

2017-01-06 10:07 UTC, closed without merging